argo-cd:
  configs:
    secret:
      argocdServerAdminPassword: "$2a$12$ryXTlXq15SNnaMYbsSHX..fyWmEYZ3CVGHBSpcOEM3af8pwoNa3mC"
  server:
    additionalApplications:
      # GRAYLOG APPLICATION
      - name: graylog
        project: default
        source:
          repoURL: https://github.com/AhmedGrati/graylog-helm-chart
          helm:
            valueFiles:
              - values.yaml
          targetRevision: HEAD
          path: graylog-helm-chart
        destination:
          server: https://kubernetes.default.svc
          namespace: monitoring
        syncPolicy:
          syncOptions:
            - CreateNamespace=true
          automated:
            selfHeal: true
            prune: true
      # ELASTIC SEARCH APPLICATION
      - name: elastic
        project: default
        source:
          repoURL: https://github.com/AhmedGrati/elastic-helm-chart
          targetRevision: HEAD
          helm:
            valueFiles:
              - values.yaml
          path: elastic-helm-chart
        destination:
          server: https://kubernetes.default.svc
          namespace: database
        syncPolicy:
          syncOptions:
            - CreateNamespace=true
          automated:
            selfHeal: true
            prune: true
      # MONGODB APPLICATION
      - name: mongodb
        project: default
        source:
          repoURL: https://github.com/AhmedGrati/mongo-helm-chart
          targetRevision: HEAD
          helm:
            valueFiles:
              - values.yaml
          path: mongo-helm-chart
        destination:
          server: https://kubernetes.default.svc
          namespace: database
        syncPolicy:
          syncOptions:
            - CreateNamespace=true
          automated:
            selfHeal: true
            prune: true
      # POSTGRESQL HELM CHART
      - name: postgresql
        project: default
        source:
          repoURL: https://github.com/AhmedGrati/postgresql-helm-chart
          targetRevision: HEAD
          helm:
            valueFiles:
              - values.yaml
          path: postgresql-helm-chart
        destination:
          server: https://kubernetes.default.svc
          namespace: database
        syncPolicy:
          syncOptions:
            - CreateNamespace=true
          automated:
            selfHeal: true
            prune: true
      # LOGSTASH APPLICATION
      - name: logstash
        project: default
        source:
          repoURL: https://github.com/AhmedGrati/logstash-helm-chart
          targetRevision: HEAD
          helm:
            valueFiles:
              - values.yaml
          path: logstash-helm-chart
        destination:
          server: https://kubernetes.default.svc
          namespace: monitoring
        syncPolicy:
          syncOptions:
            - CreateNamespace=true
          automated:
            selfHeal: true
            prune: true
      # KIBANA APPLICATION
      - name: kibana
        project: default
        source:
          repoURL: https://github.com/AhmedGrati/kibana-helm-chart
          targetRevision: HEAD
          helm:
            valueFiles:
              - values.yaml
          path: kibana-helm-chart
        destination:
          server: https://kubernetes.default.svc
          namespace: monitoring
        syncPolicy:
          syncOptions:
            - CreateNamespace=true
          automated:
            selfHeal: true
            prune: true
      # ZABBIX APPLICATION
      - name: zabbix
        project: default
        source:
          repoURL: https://github.com/AhmedGrati/zabbix-helm-chart
          targetRevision: HEAD
          helm:
            valueFiles:
              - values.yaml
          path: zabbix-helm-chart
        destination:
          server: https://kubernetes.default.svc
          namespace: monitoring
        syncPolicy:
          syncOptions:
            - CreateNamespace=true
          automated:
            selfHeal: true
            prune: true
      # ARGOCD APPLICATION
      - name: argocd
        project: default
        source:
          repoURL: https://github.com/AhmedGrati/argocd-helm-chart
          targetRevision: HEAD
          helm:
            valueFiles:
              - values.yaml
          path: argocd-helm-chart
        destination:
          server: https://kubernetes.default.svc
          namespace: argocd
        syncPolicy:
          syncOptions:
            - CreateNamespace=true
          automated:
            selfHeal: true
            prune: true

    service:
      type: NodePort